BootStrap: docker
From: nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04

%environment
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
    export PATH=/opt/conda/bin:$PATH

%post
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
    export PATH=/opt/conda/bin:$PATH

    apt update && apt install -y \
          build-essential \
          cmake \
          git mercurial subversion \
          curl \
          vim \
          ca-certificates \
          libjpeg-dev \
          libpng-dev \
          libglib2.0-0 \
          libgl1-mesa-glx \
          libxext6 \
          libsm6 \
          libxrender1 \
          libfontconfig1 \
          libibcm1 \
          libibverbs1 \
          ibverbs-utils \
          librdmacm1 \
          rdmacm-utils \
          libdapl2 \
          ibsim-utils \
          ibutils \
          libcxgb3-1 \
          libibmad5 \
          libibumad3 \
          libmlx4-1 \
          libmthca1 \
          libnes1 \
          infiniband-diags \
          mstflint \
          opensm \
          libopensm5a \
          perftest \
          srptools \
          rdmacm-utils \
          libipathverbs1 \
          libmthca1 \
          libmlx4-1 \
          libmlx5-1 \
          libnes1 \
          librdmacm1 \
          ibacm \
          infiniband-diags \
          ibutils \
          libibverbs-dev \
          libtorque2-dev

    rm -rf /var/lib/apt/lists/*

    cd ~ && \
        curl -o ~/openmpi.tar.gz -O \
        https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.2.tar.gz && \
        tar xzpvf ~/openmpi.tar.gz && \
        cd ~/openmpi-3.1.2 && \
        ./configure --with-cuda=/usr/local/cuda --enable-contrib-no-build=vt && \
        make -j 4 && \
        make install && ldconfig && \
        cd ~ && rm -rf ~/openmpi-3.1.2

    export PYTHON_VERSION=3.6
    export CONDA_INSTALL_PATH="/opt/conda"

    curl -o ~/miniconda.sh -O \
       https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
       chmod +x ~/miniconda.sh && \
       ~/miniconda.sh -b -p $CONDA_INSTALL_PATH && \
       rm ~/miniconda.sh && \
       /opt/conda/bin/conda install -y python=$PYTHON_VERSION anaconda

    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

    conda install -y pytorch torchvision cuda92 ignite -c pytorch &&
    conda install -y tensorboard
    HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache horovod augmentor

cat << EOF >> /environment 
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export PATH=/opt/conda/bin:\$PATH
EOF
