BootStrap: shub
From: nelsonihc/singularity:base1604

%environment
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
    export PATH=/opt/conda/bin:$PATH

%post
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
    export PATH=/opt/conda/bin:$PATH

    conda install -y pytorch torchvision cuda92 ignite -c pytorch
    HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache horovod
    pip install augmentor tensorboard tensorboardX PyHamcrest
